-- con, key, mouse name tables
-- loaded before bindings.lua and events.lua

local function make_ref(src, field, val)
	return { __kind = "ref", src = src, field = field, val = val }
end

con = setmetatable({
	a = make_ref("con", "a", "a"),
	b = make_ref("con", "b", "b"),
	x = make_ref("con", "x", "x"),
	y = make_ref("con", "y", "y"),
	dpad_up = make_ref("con", "dpad_up", "dpad_up"),
	dpad_down = make_ref("con", "dpad_down", "dpad_down"),
	dpad_left = make_ref("con", "dpad_left", "dpad_left"),
	dpad_right = make_ref("con", "dpad_right", "dpad_right"),
	left_shoulder = make_ref("con", "left_shoulder", "left_shoulder"),
	right_shoulder = make_ref("con", "right_shoulder", "right_shoulder"),
	left_stick = make_ref("con", "left_stick", "left_stick"),
	right_stick = make_ref("con", "right_stick", "right_stick"),
	start = make_ref("con", "start", "start"),
	back = make_ref("con", "back", "back"),
	guide = make_ref("con", "guide", "guide"),
	left_trigger = make_ref("con", "left_trigger", "left_trigger"),
	right_trigger = make_ref("con", "right_trigger", "right_trigger"),
	touchpad_click = make_ref("con", "touchpad_click", "touchpad_click"),
	touchpad_touch = make_ref("con", "touchpad_touch", "touchpad_touch"),
	misc_1 = make_ref("con", "misc_1", "misc_1"),
	paddle_1 = make_ref("con", "paddle_1", "paddle_1"),
	paddle_2 = make_ref("con", "paddle_2", "paddle_2"),
	paddle_3 = make_ref("con", "paddle_3", "paddle_3"),
	paddle_4 = make_ref("con", "paddle_4", "paddle_4"),
	left_stick_up = make_ref("con", "left_stick_up", "left_stick_up"),
	left_stick_down = make_ref("con", "left_stick_down", "left_stick_down"),
	left_stick_left = make_ref("con", "left_stick_left", "left_stick_left"),
	left_stick_right = make_ref("con", "left_stick_right", "left_stick_right"),
	right_stick_up = make_ref("con", "right_stick_up", "right_stick_up"),
	right_stick_down = make_ref("con", "right_stick_down", "right_stick_down"),
	right_stick_left = make_ref("con", "right_stick_left", "right_stick_left"),
	right_stick_right = make_ref("con", "right_stick_right", "right_stick_right"),
	left_ring_inner = make_ref("con", "left_ring_inner", "left_ring_inner"),
	left_ring_outer = make_ref("con", "left_ring_outer", "left_ring_outer"),
	right_ring_inner = make_ref("con", "right_ring_inner", "right_ring_inner"),
	right_ring_outer = make_ref("con", "right_ring_outer", "right_ring_outer"),
}, { __index = function(_, k)
	error("unknown button '" .. tostring(k) .. "' — check spelling", 2)
end })

key = setmetatable({
	esc = make_ref("key", "esc", "esc"),
	["1"] = make_ref("key", "1", "1"),
	["2"] = make_ref("key", "2", "2"),
	["3"] = make_ref("key", "3", "3"),
	["4"] = make_ref("key", "4", "4"),
	["5"] = make_ref("key", "5", "5"),
	["6"] = make_ref("key", "6", "6"),
	["7"] = make_ref("key", "7", "7"),
	["8"] = make_ref("key", "8", "8"),
	["9"] = make_ref("key", "9", "9"),
	["0"] = make_ref("key", "0", "0"),
	minus = make_ref("key", "minus", "minus"),
	equal = make_ref("key", "equal", "equal"),
	backspace = make_ref("key", "backspace", "backspace"),
	tab = make_ref("key", "tab", "tab"),
	q = make_ref("key", "q", "q"),
	w = make_ref("key", "w", "w"),
	e = make_ref("key", "e", "e"),
	r = make_ref("key", "r", "r"),
	t = make_ref("key", "t", "t"),
	y = make_ref("key", "y", "y"),
	u = make_ref("key", "u", "u"),
	i = make_ref("key", "i", "i"),
	o = make_ref("key", "o", "o"),
	p = make_ref("key", "p", "p"),
	leftbrace = make_ref("key", "leftbrace", "leftbrace"),
	rightbrace = make_ref("key", "rightbrace", "rightbrace"),
	enter = make_ref("key", "enter", "enter"),
	left_control = make_ref("key", "left_control", "left_control"),
	a = make_ref("key", "a", "a"),
	s = make_ref("key", "s", "s"),
	d = make_ref("key", "d", "d"),
	f = make_ref("key", "f", "f"),
	g = make_ref("key", "g", "g"),
	h = make_ref("key", "h", "h"),
	j = make_ref("key", "j", "j"),
	k = make_ref("key", "k", "k"),
	l = make_ref("key", "l", "l"),
	semicolon = make_ref("key", "semicolon", "semicolon"),
	apostrophe = make_ref("key", "apostrophe", "apostrophe"),
	grave = make_ref("key", "grave", "grave"),
	left_shift = make_ref("key", "left_shift", "left_shift"),
	backslash = make_ref("key", "backslash", "backslash"),
	z = make_ref("key", "z", "z"),
	x = make_ref("key", "x", "x"),
	c = make_ref("key", "c", "c"),
	v = make_ref("key", "v", "v"),
	b = make_ref("key", "b", "b"),
	n = make_ref("key", "n", "n"),
	m = make_ref("key", "m", "m"),
	comma = make_ref("key", "comma", "comma"),
	dot = make_ref("key", "dot", "dot"),
	slash = make_ref("key", "slash", "slash"),
	right_shift = make_ref("key", "right_shift", "right_shift"),
	left_alt = make_ref("key", "left_alt", "left_alt"),
	space = make_ref("key", "space", "space"),
	caps_lock = make_ref("key", "caps_lock", "caps_lock"),
	f1 = make_ref("key", "f1", "f1"),
	f2 = make_ref("key", "f2", "f2"),
	f3 = make_ref("key", "f3", "f3"),
	f4 = make_ref("key", "f4", "f4"),
	f5 = make_ref("key", "f5", "f5"),
	f6 = make_ref("key", "f6", "f6"),
	f7 = make_ref("key", "f7", "f7"),
	f8 = make_ref("key", "f8", "f8"),
	f9 = make_ref("key", "f9", "f9"),
	f10 = make_ref("key", "f10", "f10"),
	f11 = make_ref("key", "f11", "f11"),
	f12 = make_ref("key", "f12", "f12"),
	num_lock = make_ref("key", "num_lock", "num_lock"),
	scroll_lock = make_ref("key", "scroll_lock", "scroll_lock"),
	right_control = make_ref("key", "right_control", "right_control"),
	sysrq = make_ref("key", "sysrq", "sysrq"),
	right_alt = make_ref("key", "right_alt", "right_alt"),
	home = make_ref("key", "home", "home"),
	up = make_ref("key", "up", "up"),
	page_up = make_ref("key", "page_up", "page_up"),
	left = make_ref("key", "left", "left"),
	right = make_ref("key", "right", "right"),
	["end"] = make_ref("key", "end", "end"),
	down = make_ref("key", "down", "down"),
	page_down = make_ref("key", "page_down", "page_down"),
	insert = make_ref("key", "insert", "insert"),
	delete = make_ref("key", "delete", "delete"),
	left_meta = make_ref("key", "left_meta", "left_meta"),
	right_meta = make_ref("key", "right_meta", "right_meta"),
	zero = make_ref("key", "zero", "0"),
	one = make_ref("key", "one", "1"),
	two = make_ref("key", "two", "2"),
	three = make_ref("key", "three", "3"),
	four = make_ref("key", "four", "4"),
	five = make_ref("key", "five", "5"),
	six = make_ref("key", "six", "6"),
	seven = make_ref("key", "seven", "7"),
	eight = make_ref("key", "eight", "8"),
	nine = make_ref("key", "nine", "9"),
}, { __index = function(_, k)
	error("unknown key '" .. tostring(k) .. "' — check spelling", 2)
end })

mouse = setmetatable({
	left = make_ref("mouse", "left", "left_mouse"),
	right = make_ref("mouse", "right", "right_mouse"),
	middle = make_ref("mouse", "middle", "middle_mouse"),
	wheel_up = make_ref("mouse", "wheel_up", "wheel_up"),
	wheel_down = make_ref("mouse", "wheel_down", "wheel_down"),
}, { __index = function(_, k)
	error("unknown mouse button '" .. tostring(k) .. "' — check spelling", 2)
end })
